services:
  esempio-fe:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - frontend-dist:/app/nginx-sites
      - nginx-config:/app/nginx-configurations
volumes:
  frontend-dist:
    name: frontend-dist
  nginx-config:
    name: nginx-config
