services:
  esempio-fe:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - frontend-dist:/app/dist
      - nginx-config:/nginx-conf
volumes:
  frontend-dist:
  nginx-config:
