services:
  esempio-fe:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - nginx-sites:/app/nginx-sites
      - nginx-config:/app/nginx-configurations
volumes:
  nginx-sites:
    name: nginx-sites
  nginx-config:
    name: nginx-config
